name: reband_http
description: An implementation for reband_restful with http.
version: 1.0.0
homepage: https://github.com/rockyoung/reband/blob/main/engine-impls/http_impl

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10

dependency_overrides:
  # Comment before publish
  reband_restful:
    path: ../../restful