# Migrated from package:pedantic: https://github.com/dart-lang/lints

include: package:lints/recommended.yaml

# Customizing static analysis, for more informations, see:
# https://dart.dev/guides/language/analysis-options.
linter:
  rules:
    - always_declare_return_types
    - close_sinks
    - package_api_docs
    - prefer_single_quotes
